//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerShoppingCart
    {
        public int Id { get; set; }
        public string CustomerUserName { get; set; }
        public int ItemId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int NoOfItem { get; set; }
        public string ItemName { get; set; }
        public decimal ItemPrice { get; set; }
        public string ItemImageName { get; set; }
    }
}
