//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<decimal> PinCode { get; set; }
        public string AddressType { get; set; }
        public string Name { get; set; }
        public string ModileNumber { get; set; }
    }
}
