//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetailsTable
    {
        public int Id { get; set; }
        public int SpecId { get; set; }
        public string SpecName { get; set; }
        public string SpecValue { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string SpecType { get; set; }
        public string SpecTypeId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
    }
}
