//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavBarItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
    }
}
