//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public decimal OrderId { get; set; }
        public string UserName { get; set; }
        public string TypeOfPaymentMethod { get; set; }
        public string OrderAddress { get; set; }
        public int ItemId { get; set; }
        public int NoOfItem { get; set; }
        public decimal TransactionId { get; set; }
        public decimal Price { get; set; }
    }
}
