//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSystemTable
    {
        public int PaymentMethodsId { get; set; }
        public string PaymentMethods { get; set; }
    }
}
